version: 2

jobs:
  build:
    environment:
      IMAGE_NAME: myon/circleci-test
    docker:
      - image: circleci/buildpack-deps
    steps:
      - checkout
      - setup_remote_docker

      - run: docker build --pull -t $IMAGE_NAME:latest .

      - run: docker login -u "$DOCKER_USER" --password-stdin <<< "$DOCKER_PASSWORD" 
      - run: |
          tag=$(date -u +%Y%m%d)
          docker tag $IMAGE_NAME:latest $IMAGE_NAME:$tag
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$tag

workflows:
  version: 2
  build:
    jobs:
      - build
