version: 2
jobs:
  build:
    docker:
      - image: haskell:8.4.3
    steps:
      - checkout
      - run: echo "A first hello"
      - run: stack --no-terminal --version
      - run: stack --no-terminal exec ghc -- --version
      - run: ls -als
