name: nyan
on:
  push:

jobs:
  nyan:
    runs-on: ubuntu-22.04
    steps:
      - run: df -hT

      - run: |
          sudo apt-get purge -y aspnetcore-* clang-* dotnet-* google-chrome-* llvm-* mono-* mysql-* php* r-*
          sudo apt-get autoremove
          sudo rm -rf /usr/local/.ghcup /usr/local/julia*
      - run: df -hT

      - run: sudo rm -rf /usr/local/lib/android
      - run: df -hT
