name: Build and Test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kiksworks/simplecheck-env
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@main

      - run: |
          set -x
          cat /etc/os-release
          clang-format --version
          ls -las
          cat /proc/cpuinfo
          cat /proc/meminfo
