name: Build and Test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kiks/build-env
    steps:
      - uses: actions/checkout@v2

      - run: cat /etc/os-release
      - run: gcc --version
      - run: clang --version
