name: Build and Test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker.pkg.github.com/kiksworks/docker-build-env/simplecheck-env
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GH_PKG_PASSWORD }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@main

      - run: |
          set -x
          cat /etc/os-release
          clang-format --version
          ls -las
          cat /proc/cpuinfo
          cat /proc/meminfo
