name: buildx test
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - uses: docker/setup-qemu-action@master
        id: qemu
        with:
          platforms: arm64
      - uses: docker/setup-buildx-action@master

      - name: Build and push
        env:
          REGISTRY: ghcr.io
          USERNAME: ${{ github.actor }}
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker login "$REGISTRY" -u "$USERNAME" --password-stdin <<< "$PASSWORD"
          docker buildx build --platform="${{ steps.qemu.outputs.platforms }}" --push -t "$REGISTRY/tosainu/buildx-test:latest" .
          rm -rf ~/.docker
