name: Build and Test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker.pkg.github.com/kiksworks/docker-build-env/build-env:latest
    steps:
      - uses: actions/checkout@v2

      - run: cat /etc/os-release
      - run: gcc --version
      - run: clang --version

      - run: ls -las

      - run: cat /proc/cpuinfo
      - run: cat /proc/meminfo
