name: Nyan
on:
  push:

jobs:
  nyan:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/create-github-app-token@v2.2.1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          repositories: infra
      - uses: actions/checkout@v6.0.2
        with:
          repository: Tosainu/infra
          token: ${{ steps.app-token.outputs.token }}
          persist-credentials: false
      - run: gh repo view
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
      - run: |
          git switch -c automated/update-from-github-actions
          echo 'Nyan!!!!!!' > README.md
          git add -A
          git commit -m 'Hello World!'
      - run: gh pr create -B main -t 'Hello World!' -b 'Create PR from GitHub Actions!'
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
